// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// Last updated: 10/18/2012
// 

#region

using WinterLeaf.Classes;

#endregion

namespace DNT_FPS_Demo_Game_Dll.Scripts.Client
    {
    public partial class Main : TorqueScriptTemplate
        {
        [Torque_Decorations.TorqueCallBack("", "", "lightRay_Init", "", 0, 100000, true)]
        public void lightRay_Init()
            {
            console.SetVar("$LightRayPostFX::brightScalar", 0.75);
            console.SetVar("$LightRayPostFX::numSamples", 40);
            console.SetVar("$LightRayPostFX::density", 0.94);
            console.SetVar("$LightRayPostFX::weight", 5.65);
            console.SetVar("$LightRayPostFX::decay", 1.0);
            console.SetVar("$LightRayPostFX::exposure", 0.0005);
            console.SetVar("$LightRayPostFX::resolutionScale", 1.0);

            TorqueSingleton ts = new TorqueSingleton("ShaderData", "LightRayOccludeShader");
            ts.PropsAddString("DXVertexShaderFile", "shaders/common/postFx/postFxV.hlsl");
            ts.PropsAddString(" DXPixelShaderFile", "shaders/common/postFx/lightRay/lightRayOccludeP.hlsl");
            ts.Props.Add("pixVersion", "3.0");
            ts.Create(m_ts);

            ts = new TorqueSingleton("ShaderData", "LightRayShader");
            ts.PropsAddString("DXVertexShaderFile", "shaders/common/postFx/postFxV.hlsl");
            ts.PropsAddString("DXPixelShaderFile", "shaders/common/postFx/lightRay/lightRayP.hlsl");
            ts.Props.Add("pixVersion", "3.0");
            ts.Create(m_ts);

            ts = new TorqueSingleton("GFXStateBlockData", "LightRayStateBlock : PFX_DefaultStateBlock");
            ts.Props.Add("samplersDefined", "true");
            ts.Props.Add("samplerStates[0]", "SamplerClampLinear");
            ts.Props.Add("samplerStates[1]", "SamplerClampLinear");
            ts.Create(m_ts);

            console.Eval(@"
singleton PostEffect( LightRayPostFX )
{
   isEnabled = false;
   allowReflectPass = false;
        
   renderTime = ""PFXAfterDiffuse"";
   renderPriority = 0.1;
      
   shader = LightRayOccludeShader;
   stateBlock = LightRayStateBlock;
   texture[0] = ""$backBuffer"";
   texture[1] = ""#prepass"";
   target = ""$outTex"";
   targetFormat = ""GFXFormatR16G16B16A16F"";
      
   new PostEffect()
   {
      shader = LightRayShader;
      stateBlock = LightRayStateBlock;
      internalName = ""final"";
      texture[0] = ""$inTex"";
      texture[1] = ""$backBuffer"";
      target = ""$backBuffer"";
   };
};
");
            }

        [Torque_Decorations.TorqueCallBack("", "LightRayPostFX", "preProcess", "%this", 1, 100100, false)]
        public void LightRayPostFXpreProcess(string thisobj)
            {
            //  if (either)
            console.SetVar(thisobj + ".targetScale", console.GetVarString("$LightRayPostFX::resolutionScale") + " " + console.GetVarString("$LightRayPostFX::resolutionScale"));
            }

        //  private bool either = true;

        [Torque_Decorations.TorqueCallBack("", "LightRayPostFX", "setShaderConsts", "%this", 1, 100100, false)]
        public void LightRayPostFXsetShaderConsts(string thisobj)
            {
            // if (either)
                {
                PostEffect.setShaderConst(thisobj, "$brightScalar", console.GetVarString("$LightRayPostFX::brightScalar"));
                string pfx = SimSet.findObjectByInternalName(thisobj, "final", true);
                PostEffect.setShaderConst(pfx, "$numSamples", console.GetVarString("$LightRayPostFX::numSamples"));
                PostEffect.setShaderConst(pfx, "$density", console.GetVarString("$LightRayPostFX::density"));
                PostEffect.setShaderConst(pfx, "$weight", console.GetVarString("$LightRayPostFX::weight"));
                PostEffect.setShaderConst(pfx, "$decay", console.GetVarString("$LightRayPostFX::decay"));
                PostEffect.setShaderConst(pfx, "$exposure", console.GetVarString("$LightRayPostFX::exposure"));
                }
            // either = !either;
            //Thread.Sleep(5);
            }
        }
    }