// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNT or DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to DNT or DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// Last updated: 10/18/2012
// 

#region

using System;

#endregion

namespace WinterLeaf.Enums
    {
    /// <summary>
    /// The Scene Object type flags.
    /// </summary>
    [Flags]
    public enum SceneObjectTypesAsUint : uint
        {
        DefaultObjectType = 0x00000000,
        StaticObjectType = 0x00000001,
        EnvironmentObjectType = 0x00000002,
        TerrainObjectType = 0x00000004,
        InteriorObjectType = 0x00000008,
        WaterObjectType = 0x00000010,
        TriggerObjectType = 0x00000020,
        MarkerObjectType = 0x00000040,
        LightObjectType = 0x00000080,
        ZoneObjectType = 0x00000100,
        StaticShapeObjectType = 0x00000200,
        DynamicShapeObjectType = 0x00000400,
        GameBaseObjectType = 0x00000800,
        GameBaseHiFiObjectType = 0x00001000,
        ShapeBaseObjectType = 0x00002000,
        CameraObjectType = 0x00004000,
        PlayerObjectType = 0x00008000,
        ItemObjectType = 0x00010000,
        VehicleObjectType = 0x00020000,
        VehicleBlockerObjectType = 0x00040000,
        ProjectileObjectType = 0x00080000,
        ExplosionObjectType = 0x00100000,
        CorpseObjectType = 0x00200000,
        DebrisObjectType = 0x00400000,
        PhysicalZoneObjectType = 0x00800000,
        InteriorLikeObjectType = 0x01000000,
        TerrainLikeObjectType = 0x02000000,
        afxModelObjectType = 0x04000000,
        Flag28 = 0x08000000,
        Flag29 = 0x10000000,
        Flag30 = 0x20000000,
        Flag31 = 0x40000000,
        Flag32 = 0x80000000
        }

    /// <summary>
    /// The Scene Object type flags.
    /// </summary>
    [Flags]
    public enum SceneObjectTypesAsInt
        {
        DefaultObjectType = 0x00000000,
        StaticObjectType = 0x00000001,
        EnvironmentObjectType = 0x00000002,
        TerrainObjectType = 0x00000004,
        InteriorObjectType = 0x00000008,
        WaterObjectType = 0x00000010,
        TriggerObjectType = 0x00000020,
        MarkerObjectType = 0x00000040,
        LightObjectType = 0x00000080,
        ZoneObjectType = 0x00000100,
        StaticShapeObjectType = 0x00000200,
        DynamicShapeObjectType = 0x00000400,
        GameBaseObjectType = 0x00000800,
        GameBaseHiFiObjectType = 0x00001000,
        ShapeBaseObjectType = 0x00002000,
        CameraObjectType = 0x00004000,
        PlayerObjectType = 0x00008000,
        ItemObjectType = 0x00010000,
        VehicleObjectType = 0x00020000,
        VehicleBlockerObjectType = 0x00040000,
        ProjectileObjectType = 0x00080000,
        ExplosionObjectType = 0x00100000,
        CorpseObjectType = 0x00200000,
        DebrisObjectType = 0x00400000,
        PhysicalZoneObjectType = 0x00800000,
        InteriorLikeObjectType = 0x01000000,
        TerrainLikeObjectType = 0x02000000,
        afxModelObjectType = 0x04000000,
        Flag28 = 0x08000000,
        Flag29 = 0x10000000,
        Flag30 = 0x20000000,
        Flag31 = 0x40000000
        }
    }