// Copyright (C) 2012 Winterleaf Entertainment L,L,C.
// 
// THE SOFTW ARE IS PROVIDED ON AN “ AS IS” BASIS, WITHOUT W ARRANTY OF ANY KIND,
// INCLUDING WITHOUT LIMIT ATION THE W ARRANTIES OF MERCHANT ABILITY, FITNESS
// FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT . THE ENTIRE RISK AS TO THE
// QUALITY AND PERFORMANCE OF THE SOFTW ARE IS THE RESPONSIBILITY OF LICENSEE.
// SHOULD THE SOFTW ARE PROVE DEFECTIVE IN ANY RESPECT , LICENSEE AND NOT LICEN -
// SOR OR ITS SUPPLIERS OR RESELLERS ASSUMES THE ENTIRE COST OF AN Y SERVICE AND
// REPAIR. THIS DISCLAIMER OF W ARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS
// AGREEMENT. NO USE OF THE SOFTW ARE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
// 
// The use of the WinterLeaf Entertainment LLC DotNetT orque (“DNT ”) and DotNetT orque
// Customizer (“DNTC”)is governed by this license agreement (“ Agreement”).
// 
// R E S T R I C T I O N S
// 
// (a) Licensee may not: (i) create any derivative works of DNTC, including but not
// limited to translations, localizations, technology add-ons, or game making software
// other than Games; (ii) reverse engineer , or otherwise attempt to derive the algorithms
// for DNT or DNTC (iii) redistribute, encumber , sell, rent, lease, sublicense, or otherwise
// transfer rights to  DNTC; or (iv) remove or alter any tra demark, logo, copyright
// or other proprietary notices, legends, symbols or labels in DNT or DNTC; or (iiv) use
// the Software to develop or distribute any software that compete s with the Software
// without WinterLeaf Entertainment’s prior written consent; or (i iiv) use the Software for
// any illegal purpose.
// (b) Licensee may not distribute the DNTC in any manner.
// 
// LI C E N S E G R A N T .
// This license allows companies of any size, government entities or individuals to cre -
// ate, sell, rent, lease, or otherwise profit commercially from, games using executables
// created from the source code of DNT
// 
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// THE SOURCE CODE GENERATED BY DNTC CAN BE  DISTRIBUTED PUBLICLY PROVIDED THAT THE 
// DISTRIBUTOR PROVIDES  THE GENERATE SOURCE CODE FREE OF CHARGE.
// 
// THIS SOURCE CODE (DNT) CAN BE DISTRIBUTED PUBLICLY PROVIDED THAT THE DISTRIBUTOR 
// PROVIDES  THE SOURCE CODE (DNT) FREE OF CHARGE.
// **********************************************************************************
// **********************************************************************************
// **********************************************************************************
// 
// Please visit http://www.winterleafentertainment.com for more information about the project and latest updates.
// 
// Last updated: 10/18/2012
// 

#region

using System;
using System.Linq;
using WinterLeaf.Classes;

#endregion

namespace DNT_FPS_Demo_Game_Dll.Scripts.Server
    {
    public partial class Main : TorqueScriptTemplate
        {
        //-----------------------------------------------------------------------------
        // Torque
        // Copyright GarageGames, LLC 2011
        //-----------------------------------------------------------------------------

        //-----------------------------------------------------------------------------
        // Server mission loading
        //-----------------------------------------------------------------------------

        // On every mission load except the first, there is a pause after
        // the initial mission info is downloaded to the client.


        public int MissionLoadPause = 5000;
        public bool missionRunning;

        [Torque_Decorations.TorqueCallBack("", "", "initializemissionload", "()", 0, 13000, true)]
        public void Initializemissionload()
            {
            console.SetVar("$MissionLoadPause", 5000);
            }

        [Torque_Decorations.TorqueCallBack("", "", "loadMission", "( %missionName, %isFirstMission )", 2, 13000, false)]
        public void LoadMission(string missionName, bool isFirstMission)
            {
            EndMission();
            console.print("*** LOADING MISSION: " + missionName);
            console.print("*** Stage 1 load");

            // Reset all of these

            if (console.isFunction("clearCenterPrintAll"))
                ClearCenterPrintAll();
            if (console.isObject("clearBottomPrintAll"))
                ClearBottomPrintAll();
            // increment the mission sequence (used for ghost sequencing)

            console.SetVar("$missionSequence", console.GetVarInt("$missionSequence") + 1);
            //console.SetVar("$missionRunning", false);
            missionRunning = false;
            console.SetVar("$Server::MissionFile", missionName);
            Server__LoadFailMsg = "";

            // Extract mission info from the mission file,
            // including the display name and stuff to send
            // to the client.

            BuildLoadInfo(missionName);

            // Download mission info to the clients
            foreach (uint client in ClientGroup.Where(client => !GameConnection.isAIControlled(client.AsString())))
                SendLoadInfoToClient(client.AsString());

            // Now that we've sent the LevelInfo to the clients
            // clear it so that it won't conflict with the actual
            // LevelInfo loaded in the level
            ClearLoadInfo();

            // if this isn't the first mission, allow some time for the server
            // to transmit information to the clients:
            if (isFirstMission || console.GetVarString("$Server::ServerType") == "SinglePlayer")
                LoadMissionStage2();
            else
                Util._schedule(MissionLoadPause.AsString(), "0", "loadMissionStage2");
            }

        //-----------------------------------------------------------------------------
        [Torque_Decorations.TorqueCallBack("", "", "loadMissionStage2", "()", 0, 13000, false)]
        public void LoadMissionStage2()
            {
            console.print("*** Stage 2 load CSHARP");
            // Create the mission group off the ServerGroup
            console.SetVar("$instantGroup", "ServerGroup");

            // Make sure the mission exists
            string file = console.GetVarString("$Server::MissionFile");
            if (!Util.isFile(file))
                Server__LoadFailMsg = "Could not find mission " + file;
            else
                {
                // Calculate the mission CRC.  The CRC is used by the clients
                // to caching mission lighting.
                int missioncrc = Util.getFileCRC(file);
                console.SetVar("$missionCRC", missioncrc.AsString());
                //Looked at making this one a dll direct call, doesn't appear
                //it can be easily converted.
                // Exec the mission.  The MissionGroup (loaded components) is added to the ServerGroup
                Util.exec(console.GetVarString("$Server::MissionFile"), false, false);

                if (!console.isObject("MissionGroup"))
                    Server__LoadFailMsg = "No 'MissionGroup' found in mission " + file;
                }
            if (Server__LoadFailMsg != "")
                {
                // Inform clients that are already connected
                foreach (UInt32 client in ClientGroup)
                    MessageClient(client.AsString(), "MsgLoadFailed", Server__LoadFailMsg);
                return;
                }
            // Set mission name.
            if (console.isObject("theLevelInfo"))
                console.SetVar("$Server::MissionName", "theLevelInfo.levelName");

            // Mission cleanup group.  This is where run time components will reside.  The MissionCleanup
            // group will be added to the ServerGroup.

            Torque_Class_Helper tc = new Torque_Class_Helper("SimGroup", "MissionCleanup");
            tc.Create(m_ts);
            // Make the MissionCleanup group the place where all new objects will automatically be added.
            console.SetVar("$instantGroup", "MissionCleanup");
            console.pathOnMissionLoadDone();

            // Mission loading done...
            console.warn("*** Mission loaded");

            missionRunning = true;
            //Even though we track this in the CSharp, the tools use it as a flag.
            console.SetVar("$missionRunning", true);
            // Start all the clients in the mission
            foreach (UInt32 client in ClientGroup)
                {
                GameConnectionLoadMission(client.AsString());
                }

            onMissionLoaded();
            }

        //-----------------------------------------------------------------------------
        [Torque_Decorations.TorqueCallBack("", "", "endMission", "()", 0, 13000, false)]
        public void EndMission()
            {
            if (console.isObject("MissionGroup"))
                return;

            console.print("*** ENDING MISSION");
            // Inform the game code we're done.

            // Inform the clients
            foreach (uint client in ClientGroup)
                {
                GameConnectionendMission(client.AsString());
                GameConnection.resetGhosting(client.AsString());
                NetConnection.clearPaths(client.AsString());
                }

            if (console.isObject("MissionGroup"))
                console.Call("MissionGroup", "delete");
            if (console.isObject("MissionCleanup"))
                console.Call("MissionCleanup", "delete");

            console.clearServerPaths();
            }

        //-----------------------------------------------------------------------------
        [Torque_Decorations.TorqueCallBack("", "", "resetMission", "()", 0, 13000, false)]
        public void ResetMission()
            {
            console.print("*** MISSION RESET");
            // Remove any temporary mission objects
            console.Call("MissionCleanup", "delete");
            console.SetVar("$instantGroup", console.GetVarString("ServerGroup"));
            Torque_Class_Helper tcg = new Torque_Class_Helper("SimGroup", "MissionCleanup");
            string sMissionCleanup = tcg.Create(m_ts).AsString();
            console.SetVar("$instantGroup", sMissionCleanup);

            console.clearServerPaths();
            console.error("-------------> Client Group Count = " + ClientGroup.Count);
            }
        }
    }